version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5433:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports: ["9002:9000","9003:9001"]
    volumes: [minio:/data]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  api:
    build: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      REDIS_URL: ${REDIS_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      USE_OPENAI: ${USE_OPENAI}
      USE_OLLAMA: ${USE_OLLAMA}
      PRIVACY_MODE: ${PRIVACY_MODE}
      SECRET_KEY: ${SECRET_KEY}
    depends_on: [postgres, minio, redis]
    ports: ["8000:8000"]

  worker:
    build: ./backend
    command: celery -A backend.worker.celery_app worker --loglevel=INFO
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      REDIS_URL: ${REDIS_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      USE_OPENAI: ${USE_OPENAI}
      USE_OLLAMA: ${USE_OLLAMA}
      PRIVACY_MODE: ${PRIVACY_MODE}
      SECRET_KEY: ${SECRET_KEY}
    depends_on: [api, redis, minio, postgres]

  web:
    build: ./frontend
    depends_on: [api]
    ports: ["5173:5173"]

volumes:
  pgdata: {}
  minio: {}
